### ISSUE TITLE
hi, metabase v0.49.0 add doris , sync error

### ISSUE THREAD

**Issue by luchatex** [ihadoop/metabase-doris-driver#2]
102a78c-2a43-4341-b94b-8fa9b4e67bd0] 2024-03-20T11:26:12+08:00 INFO metabase.sync.util FINISHED: Sync metadata for doris Database 37 ''doris'' (103.6 ms)
[9102a78c-2a43-4341-b94b-8fa9b4e67bd0] 2024-03-20T11:26:12+08:00 WARN metabase.sync.util Error in sync step Sync metadata for doris Database 37 ''doris'',java.sql.SQLTransientConnectionException: (conn=3146) errCode = 2, detailMessage = Syntax error in line 1:,	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79),	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158),	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262),	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229),	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149),	at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:163),	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471),	at clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1090),	at clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1084),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1106),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at metabase.driver.doris$fn__108611$fn__108614.invoke(doris.clj:818),	at metabase.driver.sql_jdbc.execute$fn__78824$fn__78825.invoke(execute.clj:388),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invokeStatic(execute.clj:334),	at metabase.driver.sql_jdbc.execute$do_with_resolved_connection.invoke(execute.clj:317),	at metabase.driver.sql_jdbc.execute$fn__78824.invokeStatic(execute.clj:382),	at metabase.driver.sql_jdbc.execute$fn__78824.invoke(execute.clj:380),	at clojure.lang.MultiFn.invoke(MultiFn.java:244),	at metabase.driver.doris$fn__108611.invokeStatic(doris.clj:812),	at metabase.driver.doris$fn__108611.invoke(doris.clj:809),	at clojure.lang.MultiFn.invoke(MultiFn.java:234),	at metabase.sync.fetch_metadata$db_metadata.invokeStatic(fetch_metadata.clj:17),	at metabase.sync.fetch_metadata$db_metadata.invoke(fetch_metadata.clj:14),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_$fn__82096.invoke(sync_metadata.clj:69),	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:190),	at metabase.sync.util$do_with_error_handling.invoke(util.clj:183),	at clojure.core$partial$fn__5910.invoke(core.clj:2647),	at metabase.driver$fn__49747.invokeStatic(driver.clj:759),	at metabase.driver$fn__49747.invoke(driver.clj:759),	at clojure.lang.MultiFn.invoke(MultiFn.java:239),	at metabase.sync.util$sync_in_context$fn__60065.invoke(util.clj:166),	at metabase.sync.util$with_db_logging_disabled$fn__60062.invoke(util.clj:158),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:131),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:125),	at metabase.sync.util$with_start_and_finish_logging$fn__60049.invoke(util.clj:143),	at metabase.sync.util$with_sync_events$fn__60044.invoke(util.clj:117),	at metabase.sync.util$with_duplicate_ops_prevented$fn__60031.invoke(util.clj:89),	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:215),	at metabase.sync.util$do_sync_operation.invoke(util.clj:209),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invokeStatic(sync_metadata.clj:68),	at metabase.sync.sync_metadata$sync_db_metadata_BANG_.invoke(sync_metadata.clj:65),	at metabase.sync$sync_database_BANG_$fn__82106.invoke(sync.clj:52),	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:190),	at metabase.sync.util$do_with_error_handling.invoke(util.clj:183),	at clojure.core$partial$fn__5910.invoke(core.clj:2647),	at metabase.driver$fn__49747.invokeStatic(driver.clj:759),	at metabase.driver$fn__49747.invoke(driver.clj:759),	at clojure.lang.MultiFn.invoke(MultiFn.java:239),	at metabase.sync.util$sync_in_context$fn__60065.invoke(util.clj:166),	at metabase.sync.util$with_db_logging_disabled$fn__60062.invoke(util.clj:158),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:131),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:125),	at metabase.sync.util$with_start_and_finish_logging$fn__60049.invoke(util.clj:143),	at metabase.sync.util$with_sync_events$fn__60044.invoke(util.clj:117),	at metabase.sync.util$with_duplicate_ops_prevented$fn__60031.invoke(util.clj:89),	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:215),	at metabase.sync.util$do_sync_operation.invoke(util.clj:209),	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:51),	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37),	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:46),	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37),	at metabase.events.sync_database$publish_event_BANG__primary_method_metabase_events_sync_database_event$fn__103799.invoke(sync_database.clj:24),	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047),	at clojure.lang.AFn.call(AFn.java:18),	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),	at java.base/java.lang.Thread.run(Unknown Source),Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: errCode = 2, detailMessage = Syntax error in line 1:,	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34),	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:195),	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:178),	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:322),	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220),	... 68 more,Caused by: java.sql.SQLException: errCode = 2, detailMessage = Syntax error in line 1:,SHOW TABLES FROM ,                 ^,Encountered: EOF,Expected: IDENTIFIER,	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1693),	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1555),	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1518),	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:319),	... 69 more
[9102a78c-2a43-4341-b94b-8fa9b4e67bd0] 2024-03-20T11:26:12+08:00 INFO metabase.sync.util FINISHED: Sync doris Database 37 ''doris'' (104.9 ms)
[9102a78c-2a43-4341-b94b-8fa9b4e67bd0] 2024-03-20T11:26:12+08:00 WARN metabase.sync.util Error in sync step Sync doris Database 37 ''doris'',java.lang.ClassCastException: class java.sql.SQLTransientConnectionException cannot be cast to class clojure.lang.Associative (java.sql.SQLTransientConnectionException is in module java.sql of loader 'platform'; clojure.lang.Associative is in unnamed module of loader 'app'),	at clojure.lang.RT.assoc(RT.java:827),	at clojure.core$assoc__5481.invokeStatic(core.clj:193),	at clojure.core$assoc__5481.invoke(core.clj:192),	at metabase.sync$sync_database_BANG_$fn__82106.invoke(sync.clj:52),	at metabase.sync.util$do_with_error_handling.invokeStatic(util.clj:190),	at metabase.sync.util$do_with_error_handling.invoke(util.clj:183),	at clojure.core$partial$fn__5910.invoke(core.clj:2647),	at metabase.driver$fn__49747.invokeStatic(driver.clj:759),	at metabase.driver$fn__49747.invoke(driver.clj:759),	at clojure.lang.MultiFn.invoke(MultiFn.java:239),	at metabase.sync.util$sync_in_context$fn__60065.invoke(util.clj:166),	at metabase.sync.util$with_db_logging_disabled$fn__60062.invoke(util.clj:158),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invokeStatic(util.clj:131),	at metabase.sync.util$with_start_and_finish_logging_STAR_.invoke(util.clj:125),	at metabase.sync.util$with_start_and_finish_logging$fn__60049.invoke(util.clj:143),	at metabase.sync.util$with_sync_events$fn__60044.invoke(util.clj:117),	at metabase.sync.util$with_duplicate_ops_prevented$fn__60031.invoke(util.clj:89),	at metabase.sync.util$do_sync_operation.invokeStatic(util.clj:215),	at metabase.sync.util$do_sync_operation.invoke(util.clj:209),	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:51),	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37),	at metabase.sync$sync_database_BANG_.invokeStatic(sync.clj:46),	at metabase.sync$sync_database_BANG_.invoke(sync.clj:37),	at metabase.events.sync_database$publish_event_BANG__primary_method_metabase_events_sync_database_event$fn__103799.invoke(sync_database.clj:24),	at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047),	at clojure.lang.AFn.call(AFn.java:18),	at java.base/java.util.concurrent.FutureTask.run(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source),	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source),	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ihadoop** [comment]
hi，you can add  my wechat which account is bigdata123
